# Generated by Django 2.0.2 on 2018-02-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('messenger_id', models.BigIntegerField(default=0, unique=True)),
                ('context', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Context',
                'verbose_name_plural': 'Contexts',
            },
        ),
        migrations.AddField(
            model_name='facebookuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
